#!/usr/bin/env bash
#
# Regenerates internal/engines/pins.go: the approved engine images, each bound
# to an immutable manifest digest.
#
# This is the reviewed upgrade path. DBForge never pulls a tag, because a tag
# is mutable -- postgres:16 today and postgres:16 next month can be different
# code, and an instance created later would then run something nobody reviewed.
# Instead every image DBForge can run is named by digest in a committed file,
# and changing what DBForge runs means running this script and getting the
# resulting diff reviewed like any other code change.
#
# To approve a new version, add it to APPROVED below, run `make pins`, and send
# the diff for review. To withdraw one, delete its line and do the same.
#
# Digests are resolved from the registry's own manifest endpoint, and it is the
# *index* (multi-arch list) digest that is pinned, so one pin is correct on
# every architecture.
set -euo pipefail

# APPROVED is the allowlist: "<engine> <repository> <tag>..." per line.
# Nothing outside this list can be created, in the TUI or on the CLI.
APPROVED=$(cat <<'LIST'
postgres library/postgres 18 17 16 15 14 13
mysql    library/mysql    9 8.4 8.0
mariadb  library/mariadb  11 10.11 10.6
redis    library/redis    8 7 6.2
LIST
)

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
out=$root/internal/engines/pins.go
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# token fetches a pull token for one repository. Docker Hub requires one even
# for public images, and it is scoped to a single repository.
token() {
  curl -fsS "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$1:pull" \
    | sed -n 's/.*"token":"\([^"]*\)".*/\1/p'
}

# digest resolves <repo> <tag> to the immutable digest of its manifest index.
# A HEAD is enough: the registry answers with Docker-Content-Digest, which is
# the digest of the bytes it would have served, so nothing has to be downloaded
# or hashed here.
digest() {
  local repo=$1 tag=$2 tok=$3 d
  d=$(curl -fsS -I -H "Authorization: Bearer $tok" \
        -H 'Accept: application/vnd.oci.image.index.v1+json' \
        -H 'Accept: application/vnd.docker.distribution.manifest.list.v2+json' \
        -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
        "https://registry-1.docker.io/v2/$repo/manifests/$tag" \
      | tr -d '\r' | sed -n 's/^[Dd]ocker-[Cc]ontent-[Dd]igest: //p')
  # An empty or malformed answer must fail the run rather than write a pin that
  # pins nothing.
  case $d in
    sha256:[0-9a-f]*) [ ${#d} -eq 71 ] || { echo "malformed digest for $repo:$tag: $d" >&2; return 1; } ;;
    *) echo "no digest for $repo:$tag" >&2; return 1 ;;
  esac
  printf '%s' "$d"
}

{
  cat <<'HEADER'
// Code generated by scripts/update-pins.sh; DO NOT EDIT BY HAND.
//
// Run `make pins` to regenerate, and have the diff reviewed: this file is the
// complete list of images DBForge is allowed to run, and every one of them is
// named by an immutable digest rather than by a mutable tag.

package engines

// pins maps engine -> version tag -> the digest of that tag's manifest index,
// as resolved at the time this file was generated.
//
// The tag is kept only as the name users type and as the version the engine
// catalogue reasons about (data layout, directory mode). It is never what is
// pulled or run: PinnedRef turns it into image@sha256:..., which names exactly
// one immutable artifact for as long as the registry keeps it.
var pins = map[string]map[string]string{
HEADER

  while read -r engine repo tags; do
    [ -n "$engine" ] || continue
    tok=$(token "$repo")
    printf '\t"%s": {\n' "$engine"
    for tag in $tags; do
      d=$(digest "$repo" "$tag" "$tok")
      echo "  $engine:$tag -> $d" >&2
      printf '\t\t"%s": "%s",\n' "$tag" "$d"
    done
    printf '\t},\n'
  done <<<"$APPROVED"

  printf '}\n'
} >"$tmp"

gofmt "$tmp" >"$out"
echo "wrote $out" >&2
