// Code generated by scripts/update-pins.sh; DO NOT EDIT BY HAND.
//
// Run `make pins` to regenerate, and have the diff reviewed: this file is the
// complete list of images DBForge is allowed to run, and every one of them is
// named by an immutable digest rather than by a mutable tag.

package engines

// pins maps engine -> version tag -> the digest of that tag's manifest index,
// as resolved at the time this file was generated.
//
// The tag is kept only as the name users type and as the version the engine
// catalogue reasons about (data layout, directory mode). It is never what is
// pulled or run: PinnedRef turns it into image@sha256:..., which names exactly
// one immutable artifact for as long as the registry keeps it.
var pins = map[string]map[string]string{
	"postgres": {
		"18": "sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280",
		"17": "sha256:67f41722b7a8cbdb868a44a4995c846eddfdc2973bccb291ce937dce88ad5675",
		"16": "sha256:f1c3376c26f2609ab9f29f71f824103fe2fcd8ee0346485cb6122a4f93df6f94",
		"15": "sha256:9b1d34adbce1dd07ee6e94b4a2cf698884b89bd44a6c9c12f5da8f3acbfe4957",
		"14": "sha256:156f0b253fd61366d5fc2107ad45955027d5612f695a8436ce20167f3fa79bff",
		"13": "sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068",
	},
	"mysql": {
		"9":   "sha256:29abb0a179982e4a8928138bfc7f918af9eda64e7eeb1b1d084c1720a20159e6",
		"8.4": "sha256:85b9bf2e29cf836ecb8c2a15a935d4ba0c606631dff1dd79531a11983c638f2a",
		"8.0": "sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b",
	},
	"mariadb": {
		"11":    "sha256:8b5f33ebd85d1775657e974ed10434128bb493c80e826ceaa54074fd1a92a112",
		"10.11": "sha256:07c0aaff7396b74cb7975cba78257178d188e30f531a5db2b617c48beef13c41",
		"10.6":  "sha256:553351e202c5f01c9e703d7d1d2b037a0aedb43c4fed79b3615d9183655f02c5",
	},
	"redis": {
		"8":   "sha256:298e5b3bc566bade82f46ad5511777a4a07a294097ce16ada2f6a42be5239df5",
		"7":   "sha256:71da9275c5f3fcb97d0fa0c8c5b36cc995327265420f17a04bfd544f458059f7",
		"6.2": "sha256:143f7bfc2358911d6b36138eabfbfffea46273c5d4b5696d90e5cbf23d633cf8",
	},
}
